### ISSUE TITLE
Issues when logging in

### ISSUE THREAD

**Issue by fkblackrock** [incandenza-11/blockout2024#18]
I am consistently getting this error on sign in through the instagram bot.

The error happens both running inside docker and on the host machine.

I waited for some days and it still persists.

> Enter your Instagram password: 
Successfully logged in to Instagram.
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 359, in _send_private_request
    response.raise_for_status()
  File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://i.instagram.com/api/v1/feed/timeline/
> During handling of the above exception, another exception occurred:
> Traceback (most recent call last):
  File "/app/main.py", line 34, in <module>
    main()
  File "/app/main.py", line 30, in main
    client.block_users()
  File "/app/drivers/instagram.py", line 94, in block_users
    self._ensure_logged_in()
  File "/app/drivers/instagram.py", line 39, in _ensure_logged_in
    self.client.get_timeline_feed()  # Checking if session is valid
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/auth.py", line 242, in get_timeline_feed
    return self.private_request(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 541, in private_request
    raise e
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 526, in private_request
    self._send_private_request(endpoint, **kwargs)
  File "/usr/local/lib/python3.12/site-packages/instagrapi/mixins/private.py", line 382, in _send_private_request
    raise PleaseWaitFewMinutes(e, response=e.response, **last_json)
instagrapi.exceptions.PleaseWaitFewMinutes: Please wait a few minutes before you try again.

**Comment by fkblackrock** [comment]
It got fixed after deleting the session file:

`rm resources/cache/instagram/*-session.json`

I'll add a utility in the make file
